[package]
name = "erl_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erl_dist = "0.5"
futures = "0.3"
rand = "0.8"
smol = "1"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
dirs = "4"

[patch.'crates-io']
erl_dist = {path = "../erl_dist/"}